image: xd009642/tarpaulin:0.12.2

stages:
    - test

test:
    stage: test
    before_script:
        - apt-get update && apt-get -y install libgtk-3-dev
    script:
        - cargo tarpaulin --coveralls $COVERALLS_TOKEN
    only:
        - master
        - merge_requests
    artifacts:
        paths:
            - target/coverage/tarpaulin-report.html
            - target/coverage/cobertura.xml
        reports:
            cobertura: target/coverage/cobertura.xml