image: registry.gitlab.com/tonyfinn/olympia/test_container

stages:
    - build
    - test

test:
    cache:
        key:
            files: 
                - Cargo.lock
        paths:
            - target/debug
            - .cargo
    stage: test
    artifacts:
        paths:
            - target/coverage/tarpaulin-report.html
            - target/coverage/cobertura.xml
        reports:
            cobertura: target/coverage/cobertura.xml
    script:
        - Xvfb :1 & CARGO_HOME=./.cargo DISPLAY=:1 build/test.sh

docker_container:
    when: manual
    rules:
        -   if: '$CI_COMMIT_REF_NAME == "master"'
            changes:
            - build/test_container/*
            when: always
    image: docker:19.03.8
    stage: build
    services:
      - docker:19.03.8-dind
    script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - cd build/test_container && docker build -t $CI_REGISTRY/tonyfinn/olympia/test_container:latest .
      - docker push $CI_REGISTRY/tonyfinn/olympia/test_container:latest  