image: registry.gitlab.com/tonyfinn/olympia/test_container

stages:
    - test

test:
    cache:
        key:
            files: 
                - Cargo.lock
        paths:
            - target/debug
            - .cargo
    stage: test
    artifacts:
        paths:
            - target/coverage/tarpaulin-report.html
            - target/coverage/cobertura.xml
        reports:
            cobertura: target/coverage/cobertura.xml
    script:
        - Xvfb :1 & CARGO_HOME=./.cargo DISPLAY=:1 build/test.sh